### ISSUE TITLE
Symfony RedirectResponse throws Exception for codes other than 301, 302, 303, 307, & 308

### ISSUE THREAD

**Issue by pointybeard** [ash-jc-allen/short-url#134]
Currently, the Builder class only checks to see that the redirect code is an integer in the range of 300 to 399 (inclusive). See:

https://github.com/ash-jc-allen/short-url/blob/9fa532aa9e16a2727df033e2c95f0f03309406ef/src/Classes/Builder.php#L410

This is a problem when it comes time to create an instance of `Symfony\Component\HttpFoundation\RedirectResponse` in ShortURLController (see lines [src/Controllers/ShortURLController.php#L40:L43](https://github.com/ash-jc-allen/short-url/blob/9fa532aa9e16a2727df033e2c95f0f03309406ef/src/Controllers/ShortURLController.php#L40:L43)) since it will throw an exception for anything other than 301, 302, 303, 307, & 308 (See https://github.com/symfony/symfony/blob/6eef692c2aaefddb4c560867727f5424be16b128/src/Symfony/Component/HttpFoundation/RedirectResponse.php#L41)

Although the likelihood of a short URL being made that can trigger this exception is low, it is quite easy to do. E.g.:

```php
(new Builder())->redirectStatusCode(399)->...->make();
```

One solution is to limit the possible redirect codes in `Builder::redirectStatusCode()`. E.g.

```php
if (! in_array($statusCode, [301, 302, 303, 307, 308])) {
    throw new ShortURLException('The redirect status code must be a valid redirect HTTP status code.');
}
```

**Comment by ash-jc-allen** [comment]
I'm just dropping the same reply in here as from #135:

I like the idea of the PR making the status codes stricter for people using the package's controller. However, I think I'll hold off on this one for the time being because it would reduce the flexibility for anyone who might be using their own controller.

Although I agree it's probably unlikely that anyone's using anything other than the usual 3xx codes, I want to leave it open for any users who might not be.

But, if enough people think this is worth merging, I'll definitely reconsider it though 😄

**Comment by pointybeard** [comment]
Totally up to you, of course. My code failed because I tried to use a 304 code and unexpectedly got an exception which I had to dig around to figure out. I think it's problematic to assume users won't encounter this issue, after all, I am a user and I did.
