### ISSUE TITLE
Embracing Testing 

### ISSUE THREAD

**Issue by LogicSatinn** [ash-jc-allen/short-url#161]
Hey @ash-jc-allen, Is it possible to have factories support for the two models, ShortURL and ShortURLVisits for easier testing?? 

I mean, somebody could extend the models and add the HasFactory trait as I did, but it got confusing trying to generate data using the relationship between the two models.

What do you think @ash-jc-allen ??

**Comment by ash-jc-allen** [comment]
Hey @LogicSatinn! This is something that I've thought about myself in the past. I'm not sure what the standard approach to this would usually be.

On the one hand, as you'll already know, it only takes a couple of minutes to extend the models and add the factories.

But, on the other hand, it means that if you're using this approach it might break things like polymorphic relationships in the database. Because you'd be storing `App\Models\ShortURL` rather than `AshAllenDesign\ShortURL\Models\ShortURL`.

So I'm pretty open to any suggestions on this one. My main aim for this package is to try and keep it pain-free and easy to use, so I'm happy to take direction from devs (such as yourself) that are using this in their own projects 😄

Do you think that having model factories provided by the package would make things easier?

**Comment by LogicSatinn** [comment]
@ash-jc-allen It is absolutely necessary if somebody needs to have some tests, and of course, painlessly easy-to-use. 

On the other hand, it's also a choice to have some tests while using the package or not. 

My point is, we could make things better by providing this feature and also making it a choice. I have already looked into how we could make that happen.

**Comment by ash-jc-allen** [comment]
@LogicSatinn Yeah I agree that it could probably make testing a bit easier for anyone using the package. I think I'd class it more as a "nice-to-have" though rather than "absolutely necessary" haha! 😄

I've put a tweet to get other dev's opinions on whether they'd expect a package to provide factories, or whether you should implement them yourselves. I'll wait until I've got a bit more feedback before I go ahead with making any changes. So I'll probably come back to this in a few days.

But if we end up going forward with it, I'd be cool for you to PR the changes 🙂

**Comment by LogicSatinn** [comment]
> @LogicSatinn Yeah I agree that it could probably make testing a bit easier for anyone using the package. I think I'd class it more as a "nice-to-have" though rather than "absolutely necessary" haha! 😄
> 
> I've put a tweet to get other dev's opinions on whether they'd expect a package to provide factories, or whether you should implement them yourselves. I'll wait until I've got a bit more feedback before I go ahead with making any changes. So I'll probably come back to this in a few days.
> 
> But if we end up going forward with it, I'd be cool for you to PR the changes 🙂

Absolutely 🔥... I'll keep my eyes out on the response and hear what other devs might say about that.

**Comment by LogicSatinn** [comment]
@ash-jc-allen Hey Buddy. So, turns out Model Factories is an appreciated feature among the devs. Would you like a PR on this or would you like to do this yourself?

**Comment by ash-jc-allen** [comment]
@LogicSatinn Yeah, I agree, it looks like this is something that some people might like. I'm cool with you to make a PR if you'd like? 🙂

**Comment by LogicSatinn** [comment]
> @LogicSatinn Yeah, I agree, it looks like this is something that some people might like. I'm cool with you to make a PR if you'd like? 🙂

Sure thing @ash-jc-allen. But I'm a bit occupied for the day. I'll start working on that tomorrow.

**Comment by ash-jc-allen** [comment]
This feature has now been released as part of v7.3.0 (https://github.com/ash-jc-allen/short-url/releases/tag/v7.3.0).
