### ISSUE TITLE
Gives 404 if prefix is null

### ISSUE THREAD

**Issue by nagaralsomesh** [ash-jc-allen/short-url#198]
Hi 
Gives me 404 for other urls if prefix is set to null and if i add some prefix value then it does not give any error...I have checked other issues some of them are facing same issue.Can you please help me out with this

Thanks

**Comment by ash-jc-allen** [comment]
Hey @nagaralsomesh!

Sorry that you're having problems with the package. This is something that I need to add to the documentation.

When you use the default routes provided by the package, they're registered before your app's routes (which are probably defined in the `web.php` file).  The package's route acts as a bit of a "catch all" route because there's no prefix.

To get around this, you can set the `disable_default_route` config field to `true`. This will prevent the package's route from being registered before your app's routes. You can then add the following code to the bottom of your `web.php` routes file:

```php
\AshAllenDesign\ShortURL\Facades\ShortURL::routes();
```

Hopefully this helps? 🙂

**Comment by nagaralsomesh** [comment]
Hi @ash-jc-allen 
I tried what you said but now it is giving me this error
These are the settings that is set disable_default_route => true and prefix => null

![Screenshot from 2023-05-10 09-59-47](https://github.com/ash-jc-allen/short-url/assets/88318975/680bcc80-e763-4d66-a47d-fea2515651af)

**Comment by ash-jc-allen** [comment]
Hmmm that's strange that it's trying to use `App\Http\Controllers\AshAllenDesign\ShortURL\Controllers\ShortURLController`. It should just be trying to use `AshAllenDesign\ShortURL\Controllers\ShortURLController`.

Please could you show me how you've included the `\AshAllenDesign\ShortURL\Facades\ShortURL::routes();` in your `web.php` file? Just so that I can try and reproduce the error 🙂

**Comment by nagaralsomesh** [comment]
This is how i have included in web.php
![Screenshot from 2023-05-10 16-52-01](https://github.com/ash-jc-allen/short-url/assets/88318975/ac7d76ac-3440-4e3b-b7e6-cc6a7d1db037)
![Screenshot from 2023-05-10 16-51-33](https://github.com/ash-jc-allen/short-url/assets/88318975/9242a4ce-a0d4-4558-8d84-e3a117c81f80)

**Comment by ash-jc-allen** [comment]
Ahhh I think I _might_ have figured out the cause of the issue. In older versions of Laravel, you use to define routes like so:

```php
Route::get('/', 'HomeController@index');
```

In the `RouteServiceProvider`, there is a `namespace` property that would be prepended to all the controller names. The provider looked something like this:

```php
class RouteServiceProvider extends ServiceProvider
{
    /**
     * This namespace is applied to your controller routes.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';

    /**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();

        //
    }

    /**
     * Define the "web" routes for the application.
     *
     * These routes all receive session state, CSRF protection, etc.
     *
     * @return void
     */
    protected function mapWebRoutes()
    {
        Route::middleware('web')
             ->namespace($this->namespace)
             ->group(base_path('routes/web.php'));
    }

    // ...
}
```

This would automatically prepend `App\Http\Controllers` to start of all the web routes so they pointed to the correct class (e.g. - `App\Http\Controllers\HomeController@index`).

I can't remember when, but this was changed a few Laravel versions ago. Instead, you'd now define your routes like so:

```php
use App\Http\Controllers\HomeController;

Route::get('/', [HomeController::class, 'index']);
```

The `namespace` property and method aren't used by default in Laravel anymore and were removed (https://github.com/laravel/laravel/commit/b33852ecace72791f4bc28b8dd84c108166512bf).

Am I right in guessing that your `RouteServiceProvider` is still using the `namespace` property and method? If so, this would be causing the `App\Http\Controllers` to be added to the beginning of the package's route.

If not, I'll take another look and see if there might be something else causing it? 🙂

**Comment by ash-jc-allen** [comment]
Off the top of my head, I think the quickest solution would be to update all your routes in your `web.php` file to use the newer format. This would then allow you to remove the `namespace` method from the `RouteServiceProvider`.

Admittedly, this is probably something I should have thought of when I added this functionality, sorry!

**Comment by nagaralsomesh** [comment]
No worries man...thanks for your response .
