### ISSUE TITLE
Error: Class 'AshAllenDesign\ShortURL\Classes\Builder' not found

### ISSUE THREAD

**Issue by pratiweb** [ash-jc-allen/short-url#223]
Migrated to new server AWS having issue in class not found

**Comment by ash-jc-allen** [comment]
Hey @pratiweb! I'm sorry to hear you're having issues. But unfortunately, I don't think this is a problem with the package, sorry.

I'm going to close this for the time being because I like to keep the issues focused on just the package's issues. But if you're certain it's related to Short URL, then please feel free to get back in touch and we can investigate 🙂
