### ISSUE TITLE
Specify the amount of uses

### ISSUE THREAD

**Issue by brecht-vermeersch** [ash-jc-allen/short-url#236]
Currently you can only limit the use to single use. I would like to expand this to multiple uses. 

The cleanest option would be to change the single_use (bool) column to max_uses (int), but this would be considered a breaking change. I could look into supporting both.

If I PR'd this change, would you be willing to merge it?

**Comment by ash-jc-allen** [comment]
Hey @brecht-vermeersch! I'm really sorry for the slow reply on this one, I must have completely missed the notification 🤦‍♂️

I do quite like the idea of this feature. And if I was to build this package again from scratch, I'd probably go down the route of adding `max_visits` rather than a `single_use` field.

But I think for the time being I'll hold off on this one so I'm not tinkering too much with an existing feature that might cause hiccups for existing apps.

If enough people want this feature though, it's definitely something I'd consider accepting 😄
