### ISSUE TITLE
Make facade more Laravel-like

### ISSUE THREAD

**Issue by winkbrace** [ash-jc-allen/short-url#44]
A have a simple change request. I wonder what you think about this, so I didn't create a PR yet.

The fact that it's a builder is typically hidden by Laravel.
So my suggestion is to change the facade to:

```php
ShortUrl::to('http://destination.com')->make();
```

I guess you'd have to keep both facades alive for backwards compatibility until the next version, so this might not be important enough to you. But it sure looks a lot nicer :)

**Comment by ash-jc-allen** [comment]
Hi @winkbrace, thanks for the suggestion!

I did actually consider using ``` ShortURL ``` instead of ``` ShortURLBuilder ``` but I chose not to because I didn't want to confuse people between the facade and model (they both have the same name).

Looking back though, changing it to ``` ShortURL ``` would be pretty nice because it would look cleaner! :smile:

If you'd like to make a PR for this, I've made a ``` v3.0.0 ``` branch that you can target it at. I don't have any new features that I can add to a v3.0.0 release but it can be pulled in ready for it!

**Comment by ash-jc-allen** [comment]
This can be closed now as it has been addressed in release v3.0.0 (https://github.com/ash-jc-allen/short-url/releases/tag/v3.0.0)

**Comment by winkbrace** [comment]
Thanks and sorry for not being able to help out. My schedule suffered a lot from the Corona Quarantaine.

**Comment by ash-jc-allen** [comment]
It's no problem at all, I hope all is well!
